'use client';

import { CheckCircle, XCircle, Edit } from 'lucide-react';

interface RecommendationDisplayProps {
  recommendations: string;
  onClear: () => void;
}

export default function RecommendationDisplay({ recommendations, onClear }: RecommendationDisplayProps) {
  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold text-gray-900">🎯 AI Recommendations</h2>
        <button
          onClick={onClear}
          className="flex items-center gap-2 px-4 py-2 text-gray-600 hover:text-gray-900 transition-colors"
        >
          <XCircle className="w-5 h-5" />
          Clear
        </button>
      </div>

      <div className="bg-white p-6 rounded-lg shadow-md border border-gray-200">
        <div className="flex items-start gap-3 mb-4">
          <CheckCircle className="w-6 h-6 text-green-500 flex-shrink-0 mt-1" />
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Analysis Complete!</h3>
            <p className="text-sm text-gray-600">Here are the AI-powered recommendations:</p>
          </div>
        </div>

        <div className="bg-gray-50 p-6 rounded-lg border border-gray-200">
          <div className="prose prose-sm max-w-none">
            <pre className="whitespace-pre-wrap font-sans text-gray-800 leading-relaxed">
              {recommendations}
            </pre>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="mt-6 flex flex-wrap gap-3">
          <button className="flex items-center gap-2 px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors font-medium">
            <CheckCircle className="w-5 h-5" />
            Approve Recommendations
          </button>
          
          <button className="flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium">
            <Edit className="w-5 h-5" />
            Request Modifications
          </button>
          
          <button 
            onClick={onClear}
            className="flex items-center gap-2 px-6 py-3 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors font-medium"
          >
            <XCircle className="w-5 h-5" />
            Reject
          </button>
        </div>

        <div className="mt-4 p-4 bg-blue-50 border border-blue-200 rounded-lg">
          <p className="text-sm text-blue-800">
            <strong>Note:</strong> These recommendations are generated by AI based on current workforce data, 
            skills matching, and load distribution. Please review carefully before implementing.
          </p>
        </div>
      </div>
    </div>
  );
}

// Made with Bob
